install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-msvc.exe'
  - rust-beta-x86_64-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET RUST_BACKTRACE=1
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build -j4
  - cargo test --verbose -j4

artifacts:
  - path: target\debug\conserve.exe

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/dd8ec17dedbc09d149e8
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
