[package]
name = "conserve"
version = "0.3.1"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "http://conserve.fyi/"
repository = "https://github.com/sourcefrog/conserve/"
description = """A robust backup tool.

Conserve copies files, directories, and (on Unix) symlinks from a local source
tree, to a compressed archive directory, and retrieves them on demand.

The primary interface is the `conserve` command-line tool, and the key commands
are:

    conserve init /backup/home.conserve
    conserve backup /backup/home.conserve ~
    conserve restore /backup/home.conserve /tmp/trial-restore

"""
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"

[[bin]]
name = "conserve"
doc = false  # Conflicts with library docs which are more useful.

[dependencies]
blake2-rfc = "^0"
brotli2 = "^0"
clap = "~2.19"
clippy = {version = "0.0.103", optional = true}
error-chain = "~0.7.1"
isatty = "0.1"
log = "^0"
rustc-serialize = "^0"
spectral = "0.6.0"
tempdir = "^0"
tempfile = "^2"
term = "^0.4"
time = "^0"

[features]
default = []
sync = []  # Flush changes to disk.
bench = []  # Build benchmarks (nightly compiler only)
