[package]
name = "conserve"
version = "0.3.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "https://github.com/sourcefrog/conserve/"
repository = "https://github.com/sourcefrog/conserve/"
description = "A robust backup tool. Not for production use yet."
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"

[[bin]]
name = "conserve"
doc = true

[dependencies]
blake2-rfc = "^0"
brotli2 = "^0"
clippy = {version = "*", optional = true}
conserve_testsupport = {path = "testsupport", version = "0.3.0"}
docopt = "^0"
error-chain = "0.5"
log = "^0"
rustc-serialize = "^0"
spectral = "0.5.0"
tempdir = "^0"
tempfile = "^2"
term = "^0.4"
time = "^0"

[features]
default = []
sync = []

[workspace]
members = ["testsupport"]
