[package]
authors = ["Martin Pool <mbp@sourcefrog.net>"]
build = "build.rs"
description = "A robust backup tool."
homepage = "http://conserve.fyi/"
keywords = [
    "archive",
    "backup",
]
license = "GPL-2.0"
name = "conserve"
readme = "README.md"
repository = "https://github.com/sourcefrog/conserve/"
version = "0.5.0"

[[bin]]
doc = false
name = "conserve"

[build-dependencies]
vergen = "~0.1.0"

[dependencies]
chrono = "0.2"
clap = "~2.29"
error-chain = "0.11"
globset = "0.4"
isatty = "0.1"
proptest = "0.8.7"
rayon = "0.9"
regex = "0.2"
rustc-serialize = "^0"
snap = "0.2"
spectral = "0.6.0"
tempdir = "^0"
tempfile = "^2"
term = "0.5.1"
vergen = "2.1"
walkdir = "2"

[dependencies.blake2-rfc]
version = "0.2.18"

[features]
blake2_simd_asm = ["blake2-rfc/simd_asm"]
default = []
