[package]
name = "conserve"
version = "0.3.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "http://conserve.fyi/"
repository = "https://github.com/sourcefrog/conserve/"
description = "A robust backup tool."
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"

[[bin]]
name = "conserve"
doc = false  # Conflicts with library docs which are more useful.

[dependencies]
blake2-rfc = "^0"
brotli2 = "^0"
clippy = {version = "*", optional = true}
conserve_testsupport = {path = "testsupport", version = "0.3.0"}
docopt = "^0"
error-chain = "0.5"
isatty = "0.1"
log = "^0"
rustc-serialize = "^0"
spectral = "0.6.0"
tempdir = "^0"
tempfile = "^2"
term = "^0.4"
time = "^0"

[features]
default = []
sync = []  # Flush changes to disk.
bench = []  # Build benchmarks (nightly compiler only)

[workspace]
members = ["testsupport"]
