[package]
name = "conserve"
version = "0.2.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "https://github.com/sourcefrog/conserve/"
repository = "https://github.com/sourcefrog/conserve/"
description = "A robust backup tool. Not for production use yet."
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"

[[bin]]
name = "conserve"
doc = false

[dependencies]
blake2-rfc = "^0.2.17"
brotli2 = "^0.1"
docopt = "*"
log = "*"
rustc-serialize = "*"
tempdir = "*"
tempfile = "^2.1"
term = "0.2"
walkdir = "0.1"
