[package]
name = "conserve"
version = "0.5.1"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "http://conserve.fyi/"
repository = "https://github.com/sourcefrog/conserve/"
description = """A robust backup tool."""
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"

[[bin]]
name = "conserve"
doc = false  # Conflicts with library docs which are more useful.

[dependencies]
blake2-rfc = "0.2.18"
chrono = "0.2"
clap = "2.32"
isatty = "0.1"
rayon = "1.0.2"
regex = "0.2"
rustc-serialize = "^0"
snap = "0.2"
tempdir = "^0"
tempfile = "^2"
term = "0.5.1"
terminal_size = "0.1.8"
thousands = "0.1.2"
unicode-segmentation = "1.2.1"
walkdir = "2"
globset = "0.4"

[dev-dependencies]
spectral = "0.6.0"

[features]
default = []
blake2_simd_asm = ["blake2-rfc/simd_asm"] # Use SIMD assembly, on nightly only.
