[package]
name = "conserve"
version = "0.5.1"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "http://conserve.fyi/"
repository = "https://github.com/sourcefrog/conserve/"
description = """A robust backup tool."""
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"
build = "build.rs"

[[bin]]
name = "conserve"
doc = false  # Conflicts with library docs which are more useful.

[dependencies]
chrono = "0.2"
clap = "2.32"
error-chain = "0.11"
isatty = "0.1"
rayon = "1.0.2"
regex = "0.2"
rustc-serialize = "^0"
snap = "0.2"
spectral = "0.6.0"
tempdir = "^0"
tempfile = "^2"
term = "0.5.1"
terminal_size = "0.1.8"
thousands = "0.1.2"
unicode-segmentation = "1.2.1"
vergen = "2.1"
walkdir = "2"
globset = "0.4"

[dependencies.blake2-rfc]
version = "0.2.18"

[build-dependencies]
vergen = "~0.1.0"

[features]
default = []

# Use SIMD assembly, on nightly only.
blake2_simd_asm = ["blake2-rfc/simd_asm"]
