[package]
name = "conserve"
version = "0.4.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
homepage = "http://conserve.fyi/"
repository = "https://github.com/sourcefrog/conserve/"
description = """A robust backup tool."""
readme = "README.md"
keywords = ["archive", "backup"]
license = "GPL-2.0"
build = "build.rs"

[[bin]]
name = "conserve"
doc = false  # Conflicts with library docs which are more useful.

[dependencies]
blake2-rfc = "^0"
chrono = "0.2"
clap = "~2.19"
clippy = {version = "0.0.103", optional = true}
error-chain = "0.11"
isatty = "0.1"
log = "^0"
regex = "0.2"
rustc-serialize = "^0"
snap = "0.2"
spectral = "0.6.0"
tempdir = "^0"
tempfile = "^2"
term = "^0.4"
time = "^0"
vergen = "~0.1.0"

[build-dependencies]
vergen = "~0.1.0"

[features]
default = []
bench = []  # Build unit benchmarks (nightly compiler only)
