[package]
name = "conserve"
version = "0.2.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]

[[bin]]
name = "conserve"
doc = false

[dependencies]
blake2-rfc = "^0.2.17"
brotli2 = "^0.1"
docopt = "*"
log = "*"
rustc-serialize = "*"
tempdir = "*"
term = "0.2"
walkdir = "0.1"
