[package]
authors = ["Martin Pool <mbp@sourcefrog.net>"]
description = "A robust backup tool."
edition = "2018"
homepage = "https://github.com/sourcefrog/conserve/"
keywords = [
    "archive",
    "backup",
]
license = "GPL-2.0"
name = "conserve"
readme = "README.md"
repository = "https://github.com/sourcefrog/conserve/"
version = "0.6.0"

[[bin]]
doc = false
name = "conserve"
test = false

[dependencies]
atty = "0.2.14"
blake2-rfc = "0.2.18"
chrono = "0.4.10"
clap = "2.33.0"
globset = "0.4.4"
hex = "0.4.0"
rayon = "1.3.0"
regex = "1.3.1"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
snap = "0.2.5"
tempfile = "3.1.0"
term = "0.6.1"
terminal_size = "0.1.8"
thousands = "0.2.0"
unicode-segmentation = "1.6.0"
walkdir = "2.2.9"

[dev-dependencies]
assert_cmd = "0.12.0"
assert_fs = "0.13.1"
escargot = "0.5.0"
lazy_static = "1.4.0"
predicates = "1.0.2"
spectral = "0.6.0"

[features]
blake2_simd_asm = ["blake2-rfc/simd_asm"]
default = []

[lib]
doctest = false
